from enum import Enum
class Disease(str, Enum):
    disease1 = "儿科绪论"
    disease2 = "生长发育"
    disease3 = "儿童保健"
    disease4 = "营养和营养障碍性疾病"
    disease5 = "新生儿特点及新生儿疾病"
    disease6 = "遗传性疾病"
    disease7 = "风湿免疫性疾病"
    disease8 = "感染性疾病"
    disease9 = "结核病"
    disease10 = "消化系统疾病"
    disease11 = "呼吸系统疾病"
    disease12 = "心血管系统疾病"
    disease13 = "泌尿系统疾病"
    disease14 = "血液系统疾病"
    disease15 = "神经系统疾病"
    disease16 = "内分泌系统疾病"